# Generated by Django 5.2.5 on 2025-08-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0002_perfil_delete_emailaccout"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="cpf",
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="perfil",
            name="telefone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
